export const commonActionTypes = {
    SET_SITE_LOGO : 'SET_SITE_LOGO',
    SET_SOCIAL_MEDIA : 'SET_SOCIAL_MEDIA',
    SET_MAIN_BANNER : 'SET_MAIN_BANNER',
    SET_COUNTRIES : 'SET_COUNTRIES',
    SET_SIGNIN_MODAL_TOGGLE : 'SET_SIGNIN_MODAL_TOGGLE',
    SET_SIGNUP_MODAL_TOGGLE : 'SET_SIGNUP_MODAL_TOGGLE',
    SET_SERVICES_CATEGORY : 'SET_SERVICES_CATEGORY',
    SET_PRODUCTS_CATEGORY : 'SET_PRODUCTS_CATEGORY',
    SET_INVESTMENTS_CATEGORY : 'SET_INVESTMENTS_CATEGORY',
    SET_FOOTER_ABOUT : 'SET_FOOTER_ABOUT',
    SET_MAIN_LOADING : 'SET_MAIN_LOADING',
}