export const commonActionTypes = {
    SET_SITE_LOGO : 'SET_SITE_LOGO',
    SET_SOCIAL_MEDIA : 'SET_SOCIAL_MEDIA',
    SET_MAIN_BANNER : 'SET_MAIN_BANNER',
    SET_COUNTRIES : 'SET_COUNTRIES',
    SET_SIGNIN_MODAL_TOGGLE : 'SET_SIGNIN_MODAL_TOGGLE',
    SET_SIGNUP_MODAL_TOGGLE : 'SET_SIGNUP_MODAL_TOGGLE',
}