export const advertisementActionTypes = {
    SET_ADVERTISEMENTS : 'SET_ADVERTISEMENTS',
    SET_WANT_PARAM : 'SET_WANT_PARAM',
    SET_CATEGORY_PARAM : 'SET_CATEGORY_PARAM',
    SET_SEARCH_ITEM_PARAM : 'SET_SEARCH_ITEM_PARAM',
    SET_COUNTRY_PARAM : 'SET_COUNTRY_PARAM',
}