export const advertisementActionTypes = {
    SET_ADVERTISEMENTS : 'SET_ADVERTISEMENTS',
    SET_WANT_PARAM : 'SET_WANT_PARAM',
    SET_CATEGORY_PARAM : 'SET_CATEGORY_PARAM',
    SET_SEARCH_ITEM_PARAM : 'SET_SEARCH_ITEM_PARAM',
    SET_COUNTRY_PARAM : 'SET_COUNTRY_PARAM',
    SET_AD_POSTING_LOADING : 'SET_AD_POSTING_LOADING',
    SET_AD_ITEM_MODAL_TOGGLE : 'SET_AD_ITEM_MODAL_TOGGLE',
    SET_CLICKED_ITEM : 'SET_CLICKED_ITEM',
    SET_INQUIRY_MODAL_TOGGLE : 'SET_INQUIRY_MODAL_TOGGLE',
}