export const userActionTypes = {
    SET_USER: 'SET_USER',
    USER_SIGNIN_FAIL : 'USER_SIGNIN_FAIL',
    USER_SIGNOUT: 'USER_SIGNOUT',
    VALIDATE_TOKEN: 'VALIDATE_TOKEN',
    SET_MY_ADS: 'SET_MY_ADS',
    DELETE_AD: 'DELETE_AD'
}